### ISSUE TITLE
Pod tests fail

### ISSUE THREAD

**Issue by qha** [radiator-software/p5-net-ssleay#147]
When i try to build 1.88 the tests fail like below, this was not a problem in 1.85:

    #   Failed test 'blib/lib/Net/SSLeay/Handle.pm'
    #   at /usr/share/perl5/Test/Pod.pm line 219.
    # blib/lib/Net/SSLeay/Handle.pm (362): L<text|scheme:...> is invalid according to perlpod
    # blib/lib/Net/SSLeay/Handle.pm (368): L<text|scheme:...> is invalid according to perlpod
    # blib/lib/Net/SSLeay/Handle.pm (373): L<text|scheme:...> is invalid according to perlpod
    # Looks like you failed 1 test of 2.
    t/local/01_pod.t ....................... 
    1..2

Removing t/local/01_pod.t masks the problem by not running the failing tests.

**Comment by h-vn** [comment]
I was able to reproduce the problem, based on the above:
https://stackoverflow.com/questions/16797432/perlpod-links-dont-seem-to-work
https://www.nntp.perl.org/group/perl.perl5.porters/2019/05/msg254796.html

In short: the L syntax it complains was not supported with older pod2html and when Test::Pod is too old the test fails. With Test::Pod 1.26 I was able to reproduce your results and with 1.41 the tests completed successfully.

I'd say the best option is to use recent enough Test::Pod as opposed to changing markup in Handle.pm.

Comments anyone?

**Comment by h-vn** [comment]
CentOS 6 seems to have Test::Pod 1.40 which is just one version too old. Because it's in wide use and still supported I think the best option is to bump Test::Pod version requirement to 1.41 and skip pod tests with older versions. I took a look at the pod2html result and link looks to render reasonably well.

Thinking of it now, this seems like correct fix in any case.

**Comment by qha** [comment]
That seems like a sound plan!
