### ISSUE TITLE
Make Test failed with OpenSSL 1.1.1g

### ISSUE THREAD

**Issue by DragoSpiro98** [radiator-software/p5-net-ssleay#182]
I'm trying to install Net-SSLeay-1.88.tar.gz and make test gives this error

> Test Summary Report
> -------------------
> t/external/15_altnames.t             (Wstat: 256 Tests: 9 Failed: 1)
>   Failed test:  2
>   Non-zero exit status: 1
> Files=46, Tests=2094,  8 wallclock secs ( 0.24 usr  0.03 sys +  2.47 cusr  0.35 csys =  3.09 CPU)
> Result: FAIL
> Failed 1/46 test programs. 1/2094 subtests failed.
> Makefile:1058: recipe for target 'test_dynamic' failed
> make: *** [test_dynamic] Error 255

I have OpenSSL 1.1.1g

> OpenSSL 1.1.1g  21 Apr 2020
> built on: Sat May  2 11:21:23 2020 UTC
> platform: linux-x86_64
> options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr)
> compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG
> OPENSSLDIR: "/usr/local/ssl"
> ENGINESDIR: "/usr/local/lib/engines-1.1"
> Seeding source: os-specific

And this is Perl

> This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi

**Comment by chrisnovakovic** [comment]
Thanks for the report. We've removed `t/external/15_altnames.t` from Net-SSLeay since releasing 1.88 because its results are unreliable, and everything it tests is replicated in the local tests anyway. `t/local/32_x509_get_cert_info.t` performs more robust tests against `X509_get_subjectAltNames` (the source of your test failure), so as long as that passes, you can safely ignore this.
