### ISSUE TITLE
Next release timeframe?

### ISSUE THREAD

**Issue by DanFreed** [radiator-software/p5-net-ssleay#223]
Hello, 
When is the next stable release scheduled to be cut?  MetaCPAN shows 1.88 was released in May 2019.  

Thanks,
Dan

**Comment by chrisnovakovic** [comment]
We really need to get a fix for #219 in place before the next stable release, and that's where our focus currently is. We'll also need to do another developer release before the next stable release, since we've made major changes to the test suite since 1.89_02 and we'll need to make sure we haven't broken anything on platforms we don't regularly run tests on.

I have a pretty good idea of how to fix #219 and initial testing shows that it works reliably on every version of OpenSSL and LibreSSL we support, so I expect we should be able to get 1.89_03 out this week and then perhaps 1.90 the week after depending on what the CPAN Testers feedback is like for 1.89_03.

**Comment by DanFreed** [comment]
Any updates on this? I don't see any new issues that would keep this from being officially released.

**Comment by chrisnovakovic** [comment]
We've had reports of test failures with 1.89_03 on multiple versions of Windows, although we've been unable to reproduce them so far, and it's unlikely they'll block the next release. We're currently porting our CI from Travis to GitHub Actions, and when we get a full set of green builds on Linux via GitHub Actions, we'll release the next stable version.
