### ISSUE TITLE
Deprecation of TLS1 and TLS1.1

### ISSUE THREAD

**Issue by michal-josef-spacek** [radiator-software/p5-net-ssleay#280]
I think that's time to deprecate this two protocols. What do you think?

**Comment by h-vn** [comment]
I would continue supporting them for now. HTTPS has moved away from these, but because Net::SSLeay is used, for example, with LDAPS and other protocols, I'd say it's it's quite hard for us to do such a decision.

**Comment by michal-josef-spacek** [comment]
@h-vn Thank you for response. I understand yours thinking. 

FYI: I am working as RedHat/Fedora packager and we need to remove this support from RHEL because violation with FIPS and crypto policies. This mean relatively simple patch for removing support from tests. And in code support of this should not be functional because setting of OpenSSL in system. 

I believe that it is important to know this context.


From my perspective i understand yours

**Comment by h-vn** [comment]
If you already have patch for making it FIPS compliant, please let me know where it's available at.

**Comment by chrisnovakovic** [comment]
Depending on your definition of "deprecate", #376 allows Net::SSLeay to be built against a libssl that was compiled without support for old versions of TLS (i.e. with `OPENSSL_NO_TLS1_METHOD` and/or `OPENSSL_NO_TLS1_1_METHOD` defined). As @h-vn says, we can't withdraw support for them altogether because old versions of OpenSSL that we still need to support don't implement TLSv1.2, but this should at least allow you to consider disabling TLSv1 and TLSv1.1 in Fedora's OpenSSL without causing any problems with Net::SSLeay.
