### ISSUE TITLE
Net::SSLeay exports undefined symbols

### ISSUE THREAD

**Issue by chrisnovakovic** [radiator-software/p5-net-ssleay#316]
The following symbols are explicitly marked as exportable in Net::SSLeay, but they appear not to be defined in `SSLeay.pm`:

* `CTX_v2_new`
* `SESSION`
* `X509_STORE_CTX_set_flags`
* `add_session`
* `clear_error`
* `err`
* `flush_sessions`
* `remove_session`

`Changes` says that `CTX_v2_new` was removed in Net-SSLeay 1.75, but it still appears to exist in `SSLeay.xs` for libssl versions that define it (this one is unlike the others in that it can be defined sometimes, although the documentation implies it shouldn't be).

`Changes` says that `add_session`, `flush_sessions` and `remove_session` were all removed in Net-SSLeay 1.04, and there's no trace of them in `SSLeay.xs`.

`X509_STORE_CTX_set_flags` is a libssl function (present since OpenSSL 0.9.6) but it doesn't appear to be supported by Net-SSLeay any more - it was removed in 059109080 without a note in `Changes`.

It's not clear why `clear_error` is being exported, but the intention might have been to do with the libssl function `ERR_clear_error`.

I don't know what `SESSION` and `err` are supposed to be.

**Comment by h-vn** [comment]
> The following symbols are explicitly marked as exportable in Net::SSLeay, but they appear not to be defined in `SSLeay.pm`:

I think all of these can simply be removed from `SSLeay.pm`. I did some further investigation, please see below.

> `Changes` says that `CTX_v2_new` was removed in Net-SSLeay 1.75, but it still appears to exist in `SSLeay.xs` for libssl versions that define it (this one is unlike the others in that it can be defined sometimes, although the documentation implies it shouldn't be).

Most likely `Changes` should have simply said that it's removed for OpenSSL 1.1.0 and later. This is done by checking `OPENSSL_VERSION_NUMBER` instead of depending on `OPENSSL_NO_SSL2` which is set by a compile time switch that's no longer present with 1.1.0 and later.

To summarise: `Changes` entry was a bit too terse.
 
> `Changes` says that `add_session`, `flush_sessions` and `remove_session` were all removed in Net-SSLeay 1.04, and there's no trace of them in `SSLeay.xs`.

I have a collection of older versions, and I can confirm that. They were present in 1.03 and then commented out and finally removed completely a bit later.
 
> `X509_STORE_CTX_set_flags` is a libssl function (present since OpenSSL 0.9.6) but it doesn't appear to be supported by Net-SSLeay any more - it was removed in [0591090](https://github.com/radiator-software/p5-net-ssleay/commit/059109080aeff66fc16d0f7c6a48fde171dc486e) without a note in `Changes`.

The reason may be related to this documentation bug: [RT 39570](https://rt.cpan.org/Public/Bug/Display.html?id=39570). That is, `X509_STORE_CTX_set_flags` was incorrect and `X509_STORE_set_flags` is what should be used. OpenSSL does not document it, except of this deprecation hint on [X509_VERIFY_PARAM_set_flags()](https://www.openssl.org/docs/manmaster/man3/X509_VERIFY_PARAM_set_flags.html) manual page:

>> The above functions should be used to manipulate verification parameters instead of functions which work in specific structures such as X509_STORE_CTX_set_flags() which are likely to be deprecated in a future release.

Based on the above I don't think we need to consider bringing `X509_STORE_CTX_set_flags` back.

> It's not clear why `clear_error` is being exported, but the intention might have been to do with the libssl function `ERR_clear_error`.
> 
> I don't know what `SESSION` and `err` are supposed to be.

They were already in 0.04, don't have any earlier version :), and they were already without their respective functions. I don't think they have ever been usable.

**Comment by h-vn** [comment]
Pull request #343 should fix the incorrect exports by removing them.

`CTX_v2_new` remains as it is. The entry in 1.75 changes was clarified. There's also `SSLv2_method()` that is disabled for OpenSSL 1.0.0 and later, which I did not touch. It's not exactly correct because SSLv2 is available in versions older than 1.1.0.
