### ISSUE TITLE
t/40_npn_support.t fails when OpenSSL is compiled without NPN support

### ISSUE THREAD

**Issue by dilyanpalauzov** [radiator-software/p5-net-ssleay#471]
In cpan:: shell after calling `install Net::SSLeay` fails, for t/40_npn_support with message: 7 tests planed, 0 executed.  I have compiled OpenSSL 3.0.12 without NPN support by calling `./Configure no-nextprotoneg`.  So the local libssl.so does not support NPN and the tests are going always to fail.  The only way I got this install running, was to press Ctrl+Z in the right moment, then cpan halts, I edited t/local/40_npn_support.t .  I changed `plan tests => 7` to `plan skip_all => 'Plan B';`.

If the local OpenSSL is compiled without NPN support, then Net::SSLeay shall not instist to perform the NPN tests

**Comment by dilyanpalauzov** [comment]
As NPN was superseeded by ALPN by publishing RFC 7301 in 2014 and NPN has no RFC number, the simplest approach  is to delete the `40_npn_support.t` file.

**Comment by h-vn** [comment]
Thanks for the report. I can reproduce this and I think we'll fix it by checking for the presence of NPN functions. If they are not present, it indicates `no-nextprotoneg` was set when OpenSSL was compiled. We'd like to keep the tests so that the NPN functionality gets tested as long as it's still present in OpenSSL.
